### PR TITLE
Ink preview

### PR DESCRIPTION
**Pull request by ephread**
This PR adds a new command (_Ink: Preview the current Ink Story_) which summons an interactive preview of the current story.

There are a couple of things I'd like to improve, like the ability to specify the font family and the font size in the configuration settings, but it works fairly well as is.

#### On the technical bits

Under the hood, the preview uses inkjs (and borrow a bit of code from the templates the project provides).

I've used webpack to be able to work on the CSS, JavaScript (which will most likely be converted to TypeScript at some point) and HTML separately while bundling a single HTML file (which removes the need of dealing with local resources). This adds quite a bit of development dependencies but will be, I believe, beneficial in the long run.

The server has also been updated to accommodate the preview (details can be found in #2).

Let me know what you think!

### CODE REVIEW

**Comment by sequitur** [comment]
This is great work... does it work cross-platform or only on mac? I'll take a look at it and merge as soon as I can.

**Comment by ephread** [comment]
> This is great work... does it work cross-platform or only on mac? I'll take a look at it and merge as soon as I can.

Thanks!

The preview itself is cross-platform, but it depends on the language server ability to provide a compiled JSON. The language server is also cross-platform, but:

- will require Mono on Linux;
- will need to download the native inklecate binary on macOS (which basically embeds its own mono runtime); if it's not able to, Mono will be required.

It's a bit cumbersome and using a JavaScript port of the compiler would definitely make things easier. Sadly IFAIK none currently exist. inkjs might extends its support in the future, though.

I haven't tested again on all platforms but unless I've introduced regressions in the server, it should work everywhere.

**Comment by sequitur** [comment]
I think a better solution is to have a configurable (globally and per-project) path to an inklecate binary, that the user has to provide. Particularly because, eg, you may be using a customized inklecate or you may be using an older/newer version, or different versions on different projects. Wouldn't be a completely turnkey solution, but would save complexity, and I think downloading a native binary from the internet and running it as an automagic part of running the extension is a little iffy, no?

**Comment by ephread** [comment]
> I think a better solution is to have a configurable (globally and per-project) path to an inklecate binary, that the user has to provide. Particularly because, eg, you may be using a customized inklecate or you may be using an older/newer version, or different versions on different projects.
>
> […]
> 
> I think downloading a native binary from the internet and running it as an automagic part of running the extension is a little iffy, no?

Actually, you can already provide your own inklecate if you want to.

While the server comes bundled with the latest version, users can take advantage of the `ink.inklecateExecutablePath` configuration setting, which will accept either an absolute path or a command name if it's in the global PATH. If you found the setting to be non functional, it's a bug.

I can fully understand the concerns about pre-bundling and downloading native dependencies in the background, but it's not something unheard of in the VS Code extension community. For instance vscode-sqlite falls back to a pre-bundled SQLite if required and the OmniSharp extension conveniently downloads the native dependencies during the first run.

In the case of OmniSharp, AFAIK, users can prevent that from happening, by providing their own binary through the following setting:

```json
"omnisharp.path": {
    "type": [
        "string",
        "null"
    ],
    "default": null,
    "description": "Specifies the path to OmniSharp. This can be the absolute path to an OmniSharp executable, a specific version number, or \"latest\". If a version number or \"latest\" is specified, the appropriate version of OmniSharp will be downloaded on your behalf."
}
```

I wouldn't go as far a they go however. The pre-bundled version of inklecate is here for _convenience_, there probably wouldn't be any need to download specific versions of inklecate, as they can be provided by the user themselves (unless Ink gets a sudden surge in popularity).

On top of that, as alluded in the comment above, the Mono dependency is a bit inconvenient for people who don't use Windows. While I compiled a mac executable of inklecate –to match the convenience of inky–, it's a bit bothersome and I haven't found a way to compile (much less test) an executable working for all GNU/Linux distributions. That's why I'd like to provide these features out of the box by bundling a JavaScript port directly instead of using DLLs and executables.

This future change would not remove the support of C#-based, user-provided inklecates however. The language server still need to be useful for more advanced users.

I feel quite strongly about this sort of _convenience_. Although VS Code is more likely to be used by developers rather than writers, not all developers will necessarily be familiar with Ink in the first place. For instance, if one is only remotely familiar with C# and the .NET ecosystem, one can still enjoy the benefits of OmniSharp and start learning, without delving in the specifics. Configuring the environment to suit the growing needs can come at a later time.

---

> Particularly because, eg, you may be using a customized inklecate or you may be using an older/newer version, or different versions on different projects.

That's an entirely valid point, of which I may have lost sight when designing the preview. Indeed, the current ability to provide a custom inklecate does not extend to the preview. But your comment made me realize that with the work already laid out in the server and the client, it would be fairly straightforward to provide a preview backed by inklecate (either bundled or provided), rather than using inkjs.

So, that's what I did for the last six hours and it's working quite well. The server has been updated but I'm still polishing the client. I'll update the PR with the changes as soon as possible.

**Comment by ephread** [comment]
I've updated the PR with the changes discussed above. To keep the history clean, and remove the clutter, I've squashed three commits together.

The preview system is now handled by inklecate. It's essentially a ping-pong game between the web view and inklecate, mediated by both the language client and the language server.

I've also changed a bit VS Code's tasks, to make them play well with webpack.

**Comment by sequitur** [comment]
So I had a couple of problems getting this to run so far.

First, compiling throws this error:
```
node_modules/vscode-languageclient/lib/protocolConverter.d.ts:56:57 - error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.
```

Changing the engine version in `package.json` to `^1.25.1` seems to fix it but I'm not sure that's the correct/necessary fix or something wrong with my setup.

Once compiled, trying to run an ink preview fails silently. The language server outputs `Received play story command.` and a play preview pane opens, but nothing happens. I don't actually have Chrome installed on this machine so I didn't attach the devtools debugger the language server output mentions, I think the server needs some better error reporting before this is ready to push out to production.

**Comment by ephread** [comment]
> First, compiling throws this error:
> […]
> Changing the engine version in package.json to ^1.25.1 seems to fix it but I'm not sure that's the correct/necessary fix or something wrong with my setup.

It depends on the current version of VS Code, it's a mismatch between the API currently available and the API declared in _vscode.d.ts_ (the engine). This error is only thrown during compilation and as I far as I know won't impact users if they use an older version of the extension with a newer version of VS Code.

I wasn't sure which version of VS Code you'd have, so I left it as is. What you did is actually the correct way to fix it. From now on, I'll constantly update to the latest version of the engine, so you won't see the error thrown again.

> I don't actually have Chrome installed on this machine so I didn't attach the devtools debugger the language server output mentions.

You normally don't need Chrome. There's a debug configuration in VS Code ("Attach to Server"), which will attach a debugger to the server. You can add breakpoints to any line in `node_modules/ink-language-server/lib/*.js` and once you attach the debugger, the execution should stop when required.

> Once compiled, trying to run an ink preview fails silently. The language server outputs Received play story command. and a play preview pane opens, but nothing happens. […] I think the server needs some better error reporting before this is ready to push out to production.

That's quite interesting, I test a number of things preemptively and try to output helpful errors. Obviously you fell into a case I didn't think of, but that's a very good news. I'll be able to cover it.

To help me track down the issue, it would be useful to know the answers to these questions:

- which OS did you try this on?
- did you set any of the available configuration settings?

Thanks for your time!

**Comment by sequitur** [comment]
This was on Windows. No configurations set, running the extension in the extension host mode for VS code, using a project with just one small and simple (but valid) Ink file.

**Comment by ephread** [comment]
Should be fixed. It was a stupid mistake, a missing else clause. I'll add some tests for this specific issue, but only after instructing Travis to perform the automated tests on the three main OS.

**Comment by sequitur** [comment]
Okay, so, currently, this kinda works. It fails (with a generic "command failed" notification) when I use the Ink preview command on an extension host just after opening a file, but after a few moments and trying again ti works; race condition or no error message for when the server hasn't started up/attached yet?

When I tried it on a real, large project, the server started throwing "temporary directory for [project name] is 'undefined', ignoring" errors, though. Any clue what could be causing those?

**Comment by ephread** [comment]
> Okay, so, currently, this kinda works. It fails (with a generic "command failed" notification) when I use the Ink preview command on an extension host just after opening a file, but after a few moments and trying again ti works; race condition or no error message for when the server hasn't started up/attached yet?

Yes, sorry for that, that's exactly what's happening. The language server needs some time to spin up and a good improvement would be to handle the case properly and show an activity indicator inside the preview.

> When I tried it on a real, large project, the server started throwing "temporary directory for [project name] is 'undefined', ignoring" errors, though. Any clue what could be causing those?

Ouch, looks awfully like a workspace management issue on the server's end. Do the project use a multi-root workspace by any chance?

**Comment by sequitur** [comment]
Nope - just one root. It is a large project with a large number of files, and the main Ink file is deeply nested several/folders/deep, but it's a single-root workspace.

**Comment by ephread** [comment]
Alright, thanks for the clarification. I'll try to create a setup similar to yours and track down the issue over the week-end if I get the chance.

**Comment by sequitur** [comment]
If I have the time, I'll try to do some digging on my end and find out what's going on too.

**Comment by ephread** [comment]
I've updated the server (0.2.2), I couldn't reproduce your issue, but I've improved the logger and shuffled around some code to make errors more explicit.

I've also fixed a couple of issues related to the creation of new directories. Let me know if this makes your issue easier to track.

I didn't update `package.json` this time, but the caret range should make npm pick up the latest version (hopefully - I've had some surprise in the past).

**Comment by sequitur** [comment]
I'll try to test it out again soon and see if it throws any interesting errors (or just works - ideally it just works 😃)

**Comment by ephread** [comment]
Great! (Don't get your hopes too high, though!)

**Comment by sequitur** [comment]
Okay, I tried it again (made sure to get the 0.2.2 version of the server - I don't know from npm version specs but it did not fetch 0.2.2 until I made it, presumably because it already had 0.2.1 and that's "good enough" to satisfy "^0.2.1").

Doesn't work, but MUCH better error reporting:

```
Debugger listening on port 6009.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:6009/1fd67f77-9024-4f76-a63d-a77a0c0fd9bd
[Info  - 13:56:43] Server Initialized
[Info  - 13:56:43] Awaiting inklecate's availability before attempting a compilation…
[Info  - 13:56:43] Awaiting inklecate's availability before attempting a compilation…
[Info  - 13:56:43] Creating temporary compilation directory for: getaway
[Info  - 13:56:46] Received play story command.
[Warn  - 13:56:46] The temporary workspace does not exist, attempting to restore…
[Info  - 13:56:46] Creating temporary compilation directory for: getaway
[Error - 13:56:46] The temporary workspace is still missing, aborting command.
[Error - 13:56:46] The project could not be compiled: The temporary workspace is missing or [object Object] is not in the workspace.
```
It even threw up a notification and opened the Ink server output automatically, which is appreciated. I still don't understand what this error means (Some issue with VS code workspaces, which I don't necessarily fully understand as I believe they've been changing in the last few months). But hopefully this makes it easy to troubleshoot.

**Comment by ephread** [comment]
> But hopefully this makes it easy to troubleshoot.

It did yes, thanks for your help! The logs helped me track down two issues.

1. `[object Object]` isn't right, since the argument should be a string. This lead me to notice that I was passing URI objects directly from the client, rather than converting them to strings first. For some reasons, the URI was coerced to a string on all my setups but not on yours. That's a bit strange, but should it happen again, I've added a guard condition in the server which will log a warning with the content of the offending argument.

2. The task creating the compilation directory doesn't complete (or it completes too far in the future). There was another race condition here, as the server allowed some compilation-related code to execute without waiting for the task to complete. I've wrapped everything in Promises, so the race condition should be gone. I haven't implemented a queue, however; for now, requests from the client are simply ignored until the task completes and the user shall be informed by a short message. It more or less solves the first race condition as well.

I've also added a bit of profiling. The server will now output how long it took to create a temporary copy of the project hierarchy. The server filters files in the client workspace, based on their extension (`ink` or `ink2`), but maybe that filter is buggy. Thus, if you have a large number of files in the project, it may explain why the task did not exit fast enough in the first place.

Let me know if it takes too long to create the compilation directory (> 1-2s), there's probably something we can do about it.

The server is starting to log quite a bit of data, so I've added the `--verbose` flag, just in case. (It's enabled by default, for now.)

**Comment by sequitur** [comment]
Hey, just to let you know I haven't forgotten about this - this past week has been very hectic, but I'll get to it as soon as I am able. Thank you so much for all your work on it!

**Comment by ephread** [comment]
You're welcome. No worries! I've been busy with other tasks too.

**Comment by ephread** [comment]
I'm closing this PR, since I've put the language server on hold.

**Pull request closed without merging**
